import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hardik Sachan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Portfolio v2</h1>
    </div>
  );
}
